<a href="https://colab.research.google.com/github/RutujaBidkar/Python_Workshop/blob/main/NumpyPractices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy  as np

In [2]:
numbers = [10,20,30,40,50]

In [4]:
#Convert the list into a NumPy array.
number = np.array(numbers)
numbers

[10, 20, 30, 40, 50]

In [5]:
#Print the array.
numbers

[10, 20, 30, 40, 50]

In [11]:
#Print its data type
print(number.dtype)

int64


In [14]:
#Create a 2D array
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#Check the Shape
print(a.shape)

(2, 3)


In [16]:
#Check the Number of Dimensions
print(a.ndim)

2


In [17]:
#Check the Total Number of Elements
print(a.size)

6


In [19]:
#find the maximum value
print(a.max())

6


In [20]:
#find minimum value
print(a.min())

1


In [21]:
#Find the Sum of All Elements
print(a.sum())

21


In [24]:
#Mean calculate
print(np.mean(a))

3.5


In [25]:
#Find the stdard deviation
print(np.std(a))

1.707825127659933


In [26]:
#Create an Array of Zeros
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [27]:
#Create an array of ones
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [28]:
#Create an Array with a Range of Numbers
print(np.arange(0,10))

[1 2 3 4 5 6 7 8 9]


In [29]:
#Create Even Numbers
print(np.arange(2,20,2))

[ 2  4  6  8 10 12 14 16 18]
