<a href="https://colab.research.google.com/github/RutujaBidkar/Python_Workshop/blob/main/NumpySeriesDay2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

In [4]:
print(a[2])


30


In [7]:
print(a[0])

10


In [8]:
print(a[4])

50


In [9]:
a = np.array([5, 10, 15, 20, 25, 30])
print(a[0])
print(a[3])
print(a[5])

5
20
30


In [11]:
print(a[-1])

30


In [12]:
print(a[:3])

[ 5 10 15]


In [14]:
#Find the correct start and stop values.
print(a[0:5])

[ 5 10 15 20 25]


In [16]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a[0:5:2])

[10 30 50]


In [17]:
#reverse the array
print(a[::-1])

[60 50 40 30 20 10]


In [21]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a)
a

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(a[1,1])

5


In [30]:
print(a[0:1])

[[1 2 3]]


In [31]:
a[:0]

array([], shape=(0, 3), dtype=int64)

NameError: name 'dtype' is not defined